import Head from 'next/head';
import type { AppProps } from 'next/app';
import '@/styles/globals.css';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className="flex flex-col flex-nowrap w-full h-full">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <header className="">
        <h1 className="text-center font-medium text-lg my-4">Habit Tracker </h1>
      </header>

      <main className="flex-grow">
        <Component {...pageProps} />
      </main>
    </div>
  );
}
